# Generated by Django 5.1.6 on 2025-02-19 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userpage", "0002_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userpage.contactmessage",
            ),
        ),
    ]
